### ISSUE TITLE
DON'T WORK ON USB 3.0 MODE.

### ISSUE THREAD

**Issue by taleru** [lwfinger/rtl8812au#1]
Hello! There is a problem with the USB 3.0 mode, don't change on a USB 3.0 port.

**Comment by lwfinger** [comment]
What doesn't change? In general, any USB 2 device will work on a USB 3 port unless there is a bug in the USB driver. The client's driver is seldom the problem.

If you wish me to spend time on a bug, please do not waste my time by failing to document the fault. I should not have to beg for diagnostics. Check the output of the dmesg command for hints.

I do not have one of these devices, thus I cannot test the driver.

**Comment by taleru** [comment]
Yes, I am sorry, excuse me.

When I insert on USB 3.0 port:
[  994.559466] usb 1-1: new high-speed USB device number 4 using xhci_hcd
[  994.702204] usb 1-1: New USB device found, idVendor=0bda, idProduct=8812
[  994.702214] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  994.702219] usb 1-1: Product: 802.11n NIC
[  994.702223] usb 1-1: Manufacturer: Realtek
[  994.702228] usb 1-1: SerialNumber: 123456

When I insert on USB 2.0 port:
[ 1096.001560] usb 4-4: new high-speed USB device number 5 using ehci-pci
[ 1096.150517] usb 4-4: New USB device found, idVendor=0bda, idProduct=8812
[ 1096.150526] usb 4-4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 1096.150531] usb 4-4: Product: 802.11n NIC
[ 1096.150536] usb 4-4: Manufacturer: Realtek
[ 1096.150540] usb 4-4: SerialNumber: 123456
[ 1096.465196] rtl8812au 4-4:1.0 wlx00cbhdbb: renamed from wlan0

**Comment by taleru** [comment]
I tried it also with the rtw_switch_usb_mode=1 parameter, but it does not work with this driver.

**Comment by taleru** [comment]
On USB 3.0 port:
Bus 004 Device 002: ID 058f:6366 Alcor Micro Corp. Multi Flash Reader
Bus 004 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 006 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 005 Device 002: ID 0930:0220 Toshiba Corp. 
Bus 005 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 005: ID 0bda:8812 Realtek Semiconductor Corp. RTL8812AU 802.11a/b/g/n/ac WLAN Adapter
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

On USB 2.0 port:
Bus 004 Device 006: ID 0bda:8812 Realtek Semiconductor Corp. RTL8812AU 802.11a/b/g/n/ac WLAN Adapter
Bus 004 Device 002: ID 058f:6366 Alcor Micro Corp. Multi Flash Reader
Bus 004 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 006 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 005 Device 002: ID 0930:0220 Toshiba Corp. 
Bus 005 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

**Comment by taleru** [comment]
Before, I used this driver ( https://github.com/aircrack-ng/rtl8812au ) in all branches. I think that in all of the branches, works the USB 3.0 if we use the rtw_switch_usb_mode=1 parameter. Although the branch 5.1 the file was modified usb_intf.c of the branch 4.X and I think that it was not necessary to do so because I think that would have worked with the rtw_switch_usb_mode=1 parameter.

**Comment by taleru** [comment]
The problem in all the drivers that exist until now is that although you can connect to USB 3.0, 5000 Mbit/s, do not detect well the networks. So using USB 2.0 to scan for networks it shows a lot. But when using the USB 3.0 display only the networks whose AP is 4 meters of distance or less.

**Comment by taleru** [comment]
I don't want to make you lose time, it's just that I saw that you have a lot of experience with the drivers realtek. So I thought that you could solve the problem.

**Comment by taleru** [comment]
Also I can say that I've tested with the latest driver from realtek, rtl8812AU_linux_v5.2.9.2_24491.20171027 and also the same thing happens, USB 3.0 just detected networks if they are at a distance ridiculous.

**Comment by taleru** [comment]
In addition, I have seen this document where you can see cases in which the USB 3.0 affects the band of 2.4 G, but I don't know if it relates.

https://www.intel.com/content/dam/www/public/us/en/documents/white-papers/usb3-frequency-interference-paper.pdf

**Comment by lwfinger** [comment]
I can only debug the drivers if I have a copy of the device. For this one, I do not, and I already have too many USB devices, thus I will not buy one of these.

As a result, you need to select the driver that works best, and use it on the best port possible. If the results are unsatisfactory, then you will likely have to buy a different device. No, I will not suggest what you should buy.
