### ISSUE TITLE
insmod: ERROR: could not insert module 8812au.ko: Unknown symbol in module

### ISSUE THREAD

**Issue by SolZer** [lwfinger/rtl8812au#13]
getting the following error after insmod 8812au.ko
_insmod: ERROR: could not insert module 8812au.ko: Unknown symbol in module_

Ubuntu 18.10
4.19.0-041900-generic

**Comment by SolZer** [comment]
Commenting out `#define CONFIG_IOCTL_CFG80211` in `autoconf.h` seems to have done the trick...

**Comment by lwfinger** [comment]
Without you posting WHAT SYMBOL IS UNKNOWN, how am I supposed to help? You need to think.

**Comment by SolZer** [comment]
My apologies.  I'm new to linux.  I'll provide more information and resubmit.
