### ISSUE TITLE
ERROR: could not insert module 8812au.ko: Unknown symbol in module

### ISSUE THREAD

**Issue by SolZer** [lwfinger/rtl8812au#14]
getting the following error after `insmod 8812au.ko`

> insmod: ERROR: could not insert module 8812au.ko: Unknown symbol in module

Ubuntu 18.10
4.19.0-041900-generic

`dmesg|grep 8812au`

> [  218.101172] 8812au: loading out-of-tree module taints kernel.
> [  218.101662] 8812au: module verification failed: signature and/or required key missing - tainting kernel
> [  218.101726] 8812au: Unknown symbol cfg80211_inform_bss_frame_data (err -2)
> [  218.101765] 8812au: Unknown symbol cfg80211_scan_done (err -2)
> [  218.101792] 8812au: Unknown symbol cfg80211_remain_on_channel_expired (err -2)
> [  218.101815] 8812au: Unknown symbol cfg80211_new_sta (err -2)
> [  218.101843] 8812au: Unknown symbol wiphy_new_nm (err -2)
> [  218.101860] 8812au: Unknown symbol cfg80211_ready_on_channel (err -2)
> [  218.101880] 8812au: Unknown symbol wiphy_register (err -2)
> [  218.101897] 8812au: Unknown symbol cfg80211_put_bss (err -2)
> [  218.101913] 8812au: Unknown symbol cfg80211_roamed (err -2)
> [  218.101941] 8812au: Unknown symbol cfg80211_michael_mic_failure (err -2)
> [  218.101960] 8812au: Unknown symbol ieee80211_get_channel (err -2)
> [  218.101976] 8812au: Unknown symbol cfg80211_del_sta_sinfo (err -2)
> [  218.101995] 8812au: Unknown symbol wiphy_unregister (err -2)
> [  218.102114] 8812au: Unknown symbol cfg80211_mgmt_tx_status (err -2)
> [  218.102141] 8812au: Unknown symbol cfg80211_rx_mgmt (err -2)
> [  218.102170] 8812au: Unknown symbol ieee80211_frequency_to_channel (err -2)
> [  218.102188] 8812au: Unknown symbol wiphy_free (err -2)

Hoping this helps...  Thanks.

**Comment by SolZer** [comment]
`sudo modprobe cfg80211` fixed it.  Closing.

**Comment by lwfinger** [comment]
That is a correct fix. If you do the "sudo make install" step, then you can "sudo modprobe 8812au". For installed drivers, modprobe resolves the missing symbols. When you use insmod, that does not happen.
