### ISSUE TITLE
Two interfaces. Unable to connect from both.

### ISSUE THREAD

**Issue by Xeroxlaser** [lwfinger/rtl8812au#17]
![image](https://user-images.githubusercontent.com/36329005/54074717-525c4700-42af-11e9-87ce-2e6e7ca8b816.png)

![image](https://user-images.githubusercontent.com/36329005/54074743-8df71100-42af-11e9-8236-9c0f40f0b0b3.png)

![image](https://user-images.githubusercontent.com/36329005/54074765-ceef2580-42af-11e9-9769-ff934b6bad9a.png)

**Comment by Jibun-no-Kage** [comment]
Same issue with Debian 11 Bullseye...
Linux ancient 5.10.0-19-686-pae #1 SMP Debian 5.10.149-2 (2022-10-21) i686 GNU/Linux

Output from dmesg...
[   28.712984] rtl8812au 1-2:1.0 wlx00e04c870000: renamed from wlan0
[   28.716968] rtl8812au 1-2:1.0 wlx02e04c870000: renamed from wlan1

**Comment by lwfinger** [comment]
I disable CONCURRENT. You will get only 1 now.
