### ISSUE TITLE
Will this work with RTL8812

### ISSUE THREAD

**Issue by sanketnaik99** [lwfinger/rtl8812au#20]
I have a TP-Link Archer T4E PCI-E Wifi Card.
The entry in lspci is - Realtek Semiconductor Co., Ltd. RTL8812AE 802.11ac PCIe Wireless Network Adapter (rev 01)
Will this driver work with the card?

If you don't know whether it will work. I can test it out for you but could you guide me with the steps so that I don't end up crashing my kernel.

**Comment by lwfinger** [comment]
The last letter in the device name indicates the bus type. U stands for USB and E means PCIe. The rtl8812au driver will quietly ignore the RTL8812AE.

You have not told me what kernel you are using, but if it is at all modern, the kernel contains the driver for the RTL8812AE. It is called rtl8821ae.
