### ISSUE TITLE
Please add a LICENSE file

### ISSUE THREAD

**Issue by paralin** [lwfinger/rtl8812au#25]
Hi, please add the LICENSE file from rtl8821au:

https://github.com/aircrack-ng/rtl8812au/blob/v5.6.4.2/LICENSE

GPL-2

So that we can add it & hash it when adding a Buildroot package.

**Comment by lwfinger** [comment]
Added and pushed.

**Comment by paralin** [comment]
Thanks.

**Comment by paralin** [comment]
Ah, and a release tag - maybe something like r20220501 - that would also be useful!

Thanks again.

**Comment by lwfinger** [comment]
Done.

**Comment by paralin** [comment]
Thanks, I'll send the package to the buildroot mailing list.
