### ISSUE TITLE
make failing on 6.6.29-1-lts Arch

### ISSUE THREAD

**Issue by dulhaver** [lwfinger/rtl8812au#29]
I am trying to build this for an Arch Laptop & a  `TP-Link AC600 wireless Realtek RTL8811AU [Archer T2U Nano]` USB WLAN stick.

running on a '6.6.29-1-lts' kernel I am getting the below error

```
rtl8812au on build/240508 
❯ make
make CROSS_COMPILE= -C /lib/modules/6.6.29-1-lts/build M=/home/manolo/repos/AUR/rtl8812au  modules
make[1]: Entering directory '/home/manolo/repos/AUR/rtl8812au'
make[1]: *** /lib/modules/6.6.29-1-lts/build: No such file or directory.  Stop.
make[1]: Leaving directory '/home/manolo/repos/AUR/rtl8812au'
make: *** [Makefile:238: modules] Error 2
```

boils down to `make[1]: *** /lib/modules/6.6.29-1-lts/build: No such file or directory.  Stop.`

without real experience with kernel and kernel modules I am wondering where to start troubleshooting this. The closest I get is a directory `/usr//lib/modules/6.6.29-1-lts` which, admittedly does neither contain a directory nor file named `build`.

1. Is this even the right location to start looking?
2. is `rtl8812au` even worth trying with an `rtl8811au` stick ?

**Comment by lwfinger** [comment]
That error indicates that you have not installed the kernel headers. To do that, the following commands should work:

sudo apt-get update
sudo apt-get install make gcc linux-headers-$(uname -r) build-essential git

**Comment by dulhaver** [comment]
> That error indicates that you have not installed the kernel headers. To do that, the following commands should work:> 
> `sudo apt-get update sudo apt-get install make gcc linux-headers-$(uname -r) build-essential git`

yes, that is what I had figured out in the meantime. Just due to my current very unstable internet connect the comment I sent did not get through
