### ISSUE TITLE
make failed: cc1: error: code model kernel does not support PIC mode

### ISSUE THREAD

**Issue by wheelcomplex** [lwfinger/rtl8812au#8]
make failed in Ubuntu 18.04 with current code: https://github.com/lwfinger/rtl8812au/commit/84c178b64df793feb20540c6b42bd29c066706e2

<pre>
Linux intelwifi 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
</pre>

A previous fork is ok: https://github.com/wheelcomplex/rtl8812au-ubuntu-18.04

There are many changes between them.

<pre>
make CROSS_COMPILE= -C /lib/modules/4.15.0-20-generic/build M=/home/david/home/wifi/rtl8812au  modules
make[1]: Entering directory '/usr/src/linux-headers-4.15.0-20-generic'
  CC [M]  /home/david/home/wifi/rtl8812au/core/rtw_cmd.o
cc1: error: code model kernel does not support PIC mode
scripts/Makefile.build:332: recipe for target '/home/david/home/wifi/rtl8812au/core/rtw_cmd.o' failed
make[2]: *** [/home/david/home/wifi/rtl8812au/core/rtw_cmd.o] Error 1
Makefile:1552: recipe for target '_module_/home/david/home/wifi/rtl8812au' failed
make[1]: *** [_module_/home/david/home/wifi/rtl8812au] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-20-generic'
Makefile:238: recipe for target 'modules' failed
make: *** [modules] Error 2
</pre>

**Comment by lwfinger** [comment]
That looks like a gcc error. Certainly, nothing that I have changed modifies the PIC mode.

If you disagree, do a git bisection. That will be easy.

**Comment by wheelcomplex** [comment]
Thanks for your reply. After I install some packages for samba compiling this issue is gone. I am not sure which package is the key one.

**Comment by sachins301** [comment]
I have the same issue. how did you fix it?

**Comment by lwfinger** [comment]
Your kernel needs to be rebuilt. That is what I do.
